---
# ===================================================
# handlers file for pg_replica
# ===================================================
- name: Restart PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: restarted
