---
# ===================================================
# handlers file for pg_master
# ===================================================
- name: Restart PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: restarted

